### ISSUE TITLE
Fork sumiu

### ISSUE THREAD

**Issue by ingridtartaglia** [B2W-BIT/frontend-interview#1]
Olá,

eu fiz o desafio e na hora de mandar o pull request ontem esse repositório aqui tinha sumido (estava dando 404), e estava dizendo que eu fiz o fork a partir do Jebarretto1/frontend-interview

Mandei e-mail para o rh, mas não tive resposta. Aí agora procurei novamente e consegui achar esse repositório. Mas meu repositório não está mais na árvore de forks, e eu não consigo mandar o pull request.

Posso refazer o fork a partir desse e commitar pra cá pra fazer o pull request? Envio o pull request pro Jebarretto1 mesmo? 
Vocês podem ver o que fiz aqui:
https://github.com/ingridtartaglia/frontend-interview/tree/my-solutions

Obrigada,

Ingrid

**Comment by candreoliveira** [comment]
Olá Ingrid,

Muito obrigado pelo email.

Eu recebi o seu repositório. Vou verificar o que pode ter acontecido. Mas,
fique tranquila eu já estou com o seu código. Vamos analisar o seu desafio
e entramos em contato o mais rápido possível.

Boa sorte! :)

Abraços,
-- 

Carlos André Baptistacarlos.baptista@b2wdigital.com
21 99822-7553

B2W Digital
http://b2wdigital.com
21 3504-7202


2016-06-30 16:07 GMT-03:00 Ingrid <notifications@github.com>:
